# This is a basic workflow that is manually triggered

name: Manual workflow
uses: distributhor/workflow-webhook@v1
  env:
    webhook_url: ${{ secrets.WEBHOOK_URL }}
    webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
